### PR TITLE
Fix org.Hs.es.db variable names

### PR DESCRIPTION
**Pull request by sambrightman**

### CODE REVIEW

**Comment by sawibo** [comment]
Hi Sam,

I don't quite get what this is supposed to fix, can you elaborate ?

Best,

Sander

**Comment by sambrightman** [comment]
`$annotationdb.egSYMBOL` does not expand to a valid variable for package `org.Hs.es.db`. You can see that part of the logic to shorten the package name to be the variable prefix was added - `$shortname` is assigned in the correct way. However, it is not used anywhere. It should be used here to make the correct variable name.

Looks like changing the PR target makes Github think I want to merge all of Annelies' commits too. I will rebase the PR onto develop and see if that helps.

**Comment by sawibo** [comment]
Ah, I see now. So I already moved the PR  to develop but the behaviour of Github wanting to merge all of Annelies' requests is a bit weird.

**Comment by sambrightman** [comment]
I rebased to develop and force-pushed my branch. Looks like it has updated properly now.

**Pull request merged**
